import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import './globals.css';

import { Footer, NavBar } from '@/components';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Jacobo Jaramillo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.className} antialiased flex flex-col h-full`}>
        <NavBar />
        <div className='mb-5 mt-12 px-12 flex-1'>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
